"""Tests for uio.core.attribution — template rendering and system-prompt injection."""

from uio.core.attribution import (
    IDENTITY_DISPLAY_NAMES,
    build_attribution_instructions,
    render_comment_footer,
    render_commit_author,
    render_pr_footer,
)


def test_comment_footer_contains_display_name():
    footer = render_comment_footer("planner", "github-planner", "0.1.0")
    assert "AI Planner" in footer
    assert "github-planner" in footer
    assert "0.1.0" in footer


def test_comment_footer_no_version():
    footer = render_comment_footer("coder", "github-coder")
    assert "AI Coder" in footer
    assert "uio" not in footer.split("Generated by")[0]  # version part absent


def test_comment_footer_starts_with_separator():
    footer = render_comment_footer("reviewer", "github-reviewer")
    assert footer.startswith("\n---\n")


def test_pr_footer_contains_display_name():
    footer = render_pr_footer("coder")
    assert "AI Coder" in footer
    assert "Human review is required" in footer
    assert "uio" in footer


def test_pr_footer_all_roles():
    for role in ("planner", "coder", "reviewer"):
        footer = render_pr_footer(role)
        assert IDENTITY_DISPLAY_NAMES[role] in footer


def test_render_commit_author_coder():
    author = render_commit_author("coder")
    assert author["name"] == "uio AI Coder"
    assert "uio-coder[bot]" in author["email"]


def test_render_commit_author_returns_copy():
    a = render_commit_author("planner")
    b = render_commit_author("planner")
    a["name"] = "tampered"
    assert b["name"] != "tampered"


def test_build_attribution_instructions_contains_footer():
    block = build_attribution_instructions("planner", "github-planner", "0.1.0")
    assert "AI Planner" in block
    assert "🤖" in block
    assert "github-planner" in block


def test_build_attribution_instructions_coder_includes_commit_author():
    block = build_attribution_instructions("coder", "github-coder", "0.1.0")
    assert "user.name" in block
    assert "uio AI Coder" in block
    assert "uio-coder[bot]" in block


def test_build_attribution_instructions_non_coder_no_commit_section():
    for role in ("planner", "reviewer"):
        block = build_attribution_instructions(role, "agent", "0.1.0")
        assert "user.name" not in block


def test_build_attribution_instructions_includes_pr_footer_for_coder():
    block = build_attribution_instructions("coder", "github-coder", "0.1.0")
    assert "AI-generated pull request" in block


def test_build_attribution_instructions_all_roles_valid():
    for role in ("planner", "coder", "reviewer"):
        block = build_attribution_instructions(role, "test-agent")
        assert len(block) > 100
        assert IDENTITY_DISPLAY_NAMES[role] in block
