"""AI attribution templates and system-prompt injection for GitHub App identities.

When an agent declares ``github-identity``, the runner injects an attribution
block into the system prompt instructing the LLM to append identity footers to
all GitHub content it generates (issue comments, PR comments, PR bodies, commits).
"""

from __future__ import annotations

from typing import Final

IDENTITY_DISPLAY_NAMES: Final[dict[str, str]] = {
    "planner": "AI Planner",
    "coder": "AI Coder",
    "reviewer": "AI Reviewer",
}

# Non-human author identity for git commits created by the AI Coder.
COMMIT_AUTHOR: Final[dict[str, dict[str, str]]] = {
    "planner": {
        "name": "uio AI Planner",
        "email": "uio-planner[bot]@users.noreply.github.com",
    },
    "coder": {
        "name": "uio AI Coder",
        "email": "uio-coder[bot]@users.noreply.github.com",
    },
    "reviewer": {
        "name": "uio AI Reviewer",
        "email": "uio-reviewer[bot]@users.noreply.github.com",
    },
}


def render_comment_footer(role: str, agent_name: str, version: str = "") -> str:
    """One-line footer for GitHub issue and PR comments."""
    display = IDENTITY_DISPLAY_NAMES[role]
    version_part = f" · uio {version}" if version else ""
    return f"\n---\n🤖 Generated by **uio / {display}** · {agent_name}{version_part}"


def render_pr_footer(role: str) -> str:
    """Disclosure block for AI-generated PR descriptions."""
    display = IDENTITY_DISPLAY_NAMES[role]
    return (
        "\n---\n"
        f"> **AI-generated pull request** — authored by the uio {display} agent.\n"
        "> Human review is required before merging.\n"
        "> Powered by [uio](https://github.com/jomkz/uio)."
    )


def render_commit_author(role: str) -> dict[str, str]:
    """Return the git author name and email for the given App identity."""
    return dict(COMMIT_AUTHOR[role])


def build_attribution_instructions(role: str, agent_name: str, version: str = "") -> str:
    """Return the attribution instructions block injected into the system prompt.

    The block instructs the LLM to append the correct footer to every piece of
    GitHub content it generates, so agent authors do not need to add it manually.
    """
    display = IDENTITY_DISPLAY_NAMES[role]
    comment_footer = render_comment_footer(role, agent_name, version)
    pr_footer = render_pr_footer(role)
    author = COMMIT_AUTHOR[role]

    commit_section = ""
    if role == "coder":
        commit_section = f"""\
- **Commits** — set the git author for every commit you create:
  ```
  git -c user.name="{author["name"]}" -c user.email="{author["email"]}" commit …
  ```
  Never use `git commit` without the `-c user.name` / `-c user.email` flags when running as this identity.

"""

    return f"""\
## ℹ️ Attribution — {display}

You are acting as the **uio {display}** GitHub App identity.
Every piece of GitHub content you create must carry an attribution footer so that
AI-generated activity is clearly distinguishable from human activity.

### Rules

- **Issue comments and PR comments** — append the following footer verbatim to the
  body of every `gh issue comment`, `gh pr comment`, `mcp__github__create_issue_comment`,
  or equivalent call:
  ```
{comment_footer}
  ```

- **Pull request bodies** — when creating or editing a PR, append this block at the
  end of the PR body:
  ```
{pr_footer}
  ```

{commit_section}### Why this matters

The `{role}` identity is a non-human GitHub App (`uio-ai-{role}`). Attribution footers
make AI authorship transparent to human reviewers and are required by the project
governance policy.

---
"""
