"""AI attribution templates and system-prompt injection for VCS identity agents.

When an agent declares ``vcs-identity``, the runner injects an attribution
block into the system prompt instructing the LLM to append identity footers to
all VCS content it generates (issue comments, PR/MR comments, PR/MR bodies, commits).
"""

from __future__ import annotations

from typing import Final

IDENTITY_DISPLAY_NAMES: Final[dict[str, str]] = {
    "planner": "AI Planner",
    "coder": "AI Coder",
    "reviewer": "AI Reviewer",
}

# Non-human author identity for git commits created by the AI Coder.
COMMIT_AUTHOR: Final[dict[str, dict[str, str]]] = {
    "planner": {
        "name": "uio AI Planner",
        "email": "uio-planner[bot]@users.noreply.github.com",
    },
    "coder": {
        "name": "uio AI Coder",
        "email": "uio-coder[bot]@users.noreply.github.com",
    },
    "reviewer": {
        "name": "uio AI Reviewer",
        "email": "uio-reviewer[bot]@users.noreply.github.com",
    },
}

# Provider-specific commit email overrides (GitHub is the default in COMMIT_AUTHOR).
_PROVIDER_COMMIT_EMAILS: Final[dict[str, dict[str, str]]] = {
    "gitlab": {
        "planner": "uio-planner[bot]@users.noreply.gitlab.com",
        "coder": "uio-coder[bot]@users.noreply.gitlab.com",
        "reviewer": "uio-reviewer[bot]@users.noreply.gitlab.com",
    },
}


def render_comment_footer(role: str, agent_name: str, version: str = "") -> str:
    """One-line footer for VCS issue and PR/MR comments."""
    display = IDENTITY_DISPLAY_NAMES[role]
    version_part = f" · uio {version}" if version else ""
    return f"\n---\n🤖 Generated by **uio / {display}** · {agent_name}{version_part}"


def render_pr_footer(role: str) -> str:
    """Disclosure block for AI-generated PR/MR descriptions."""
    display = IDENTITY_DISPLAY_NAMES[role]
    return (
        "\n---\n"
        f"> **AI-generated pull request** — authored by the uio {display} agent.\n"
        "> Human review is required before merging.\n"
        "> Powered by [uio](https://github.com/jomkz/uio)."
    )


def render_commit_author(role: str, vcs_provider: str = "github") -> dict[str, str]:
    """Return the git author name and email for the given identity and VCS provider."""
    author = dict(COMMIT_AUTHOR[role])
    provider_emails = _PROVIDER_COMMIT_EMAILS.get(vcs_provider)
    if provider_emails and role in provider_emails:
        author["email"] = provider_emails[role]
    return author


def build_attribution_instructions(
    role: str, agent_name: str, version: str = "", vcs_provider: str = "github"
) -> str:
    """Return the attribution instructions block injected into the system prompt.

    The block instructs the LLM to append the correct footer to every piece of
    VCS content it generates, so agent authors do not need to add it manually.
    """
    display = IDENTITY_DISPLAY_NAMES[role]
    comment_footer = render_comment_footer(role, agent_name, version)
    pr_footer = render_pr_footer(role)
    author = render_commit_author(role, vcs_provider)

    if vcs_provider == "gitlab":
        platform_label = "GitLab identity"
        platform_content = "GitLab content"
        comment_tools = "`mcp__gitlab__create_note` or equivalent call"
        pr_term = "Merge request"
        pr_short = "MR"
        bot_kind = "non-human GitLab bot"
    else:
        platform_label = "GitHub App identity"
        platform_content = "GitHub content"
        comment_tools = (
            "`gh issue comment`, `gh pr comment`, `mcp__github__create_issue_comment`,"
            "\n  or equivalent call"
        )
        pr_term = "Pull request"
        pr_short = "PR"
        bot_kind = "non-human GitHub App"

    commit_section = ""
    if role == "coder":
        commit_section = f"""\
- **Commits** — set the git author for every commit you create:
  ```
  git -c user.name="{author["name"]}" -c user.email="{author["email"]}" commit …
  ```
  Never use `git commit` without the `-c user.name` / `-c user.email` flags when running as this identity.

"""

    return f"""\
## ℹ️ Attribution — {display}

You are acting as the **uio {display}** {platform_label}.
Every piece of {platform_content} you create must carry an attribution footer so that
AI-generated activity is clearly distinguishable from human activity.

### Rules

- **Issue comments and {pr_short} comments** — append the following footer verbatim to the
  body of every {comment_tools}:
  ```
{comment_footer}
  ```

- **{pr_term} bodies** — when creating or editing a {pr_short}, append this block at the
  end of the {pr_short} body:
  ```
{pr_footer}
  ```

{commit_section}### Why this matters

The `{role}` identity is a {bot_kind} (`uio-ai-{role}`). Attribution footers
make AI authorship transparent to human reviewers and are required by the project
governance policy.

---
"""
